version: '3.3'
  
services:
    flask:
        build: .
        image: python
        command:
          - pip install -r requirements.txt
        ports:
            - "8000:8000"
        entrypoint: python ./main.py
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - "27017:27017"